// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaJvenLe7zh2ggZvSpB6W3bJqglABacn8',
    appId: '1:345066094240:web:81dbc7f53f5a9d389fd3c5',
    messagingSenderId: '345066094240',
    projectId: 'graduation-project-77bea',
    authDomain: 'graduation-project-77bea.firebaseapp.com',
    storageBucket: 'graduation-project-77bea.appspot.com',
    measurementId: 'G-NNSX1TPJNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZrB6bkcHZ2PKkTqraJq7iRu7dM54Zeso',
    appId: '1:345066094240:android:832e988a5ff500ae9fd3c5',
    messagingSenderId: '345066094240',
    projectId: 'graduation-project-77bea',
    storageBucket: 'graduation-project-77bea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApTjiiSR8_wAjAmj8TEXNwEDn-oxhsz18',
    appId: '1:345066094240:ios:1ba60881acb702d79fd3c5',
    messagingSenderId: '345066094240',
    projectId: 'graduation-project-77bea',
    storageBucket: 'graduation-project-77bea.appspot.com',
    iosClientId: '345066094240-bj15dq31cd5lj1osuoo7hs1qbq09g7re.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduateproject',
  );
}
